import { Router, type IRouter, type Request, type Response } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import instagramRouter from "./instagram";
import landingRouter from "./landing";
import brandAuthRouter from "./brandAuth";
import brandProfileRouter from "./brandProfile";
import categoriesRouter from "./categories";
import brandSignupFieldsRouter from "./brandSignupFields";
import adminBrandsRouter from "./adminBrands";
import adminAuthRouter from "./adminAuth";
import adminConfigRouter from "./adminConfig";
import adminCategoriesRouter from "./adminCategories";
import creatorAuthRouter from "./creatorAuth";
import creatorSignupConfigRouter from "./creatorSignupConfig";
import creatorProfileRouter from "./creatorProfile";
import adminCreatorsRouter from "./adminCreators";
import slabsRouter from "./slabs";
import infoMessagesRouter from "./infoMessages";
import creatorSignupFieldsRouter from "./creatorSignupFields";
import creatorHomeRouter from "./creatorHome";
import adminRejectionReasonsRouter from "./adminRejectionReasons";
import adminFunQuestionsRouter from "./adminFunQuestions";
import messagesAndTeamRouter from "./messagesAndTeam";
import brandSearchRouter from "./brandSearch";
import matchmakingRouter from "./matchmaking";
import campaignsRouter from "./campaigns";
import adminSettingsRouter from "./adminSettings";
import dealsNegotiationRouter from "./dealsNegotiation";
import dealChatRouter from "./dealChat";
import dealShippingRouter from "./dealShipping";
import dealPipelineRouter from "./dealPipeline";
import adminRevisionReasonsRouter from "./adminRevisionReasons";
import navBadgesRouter from "./navBadges";
import storageRouter from "./storage";
import uploadImageRouter from "./uploadImage";
import uploadFileRouter from "./uploadFile";
import fcmTokenRouter from "./fcmToken";
import creatorBrandProfileRouter from "./creatorBrandProfile";
import dealExtensionsRouter from "./dealExtensions";
import brandReportsRouter from "./brandReports";
import dealReportsRouter from "./dealReports";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(adminAuthRouter);
router.use(instagramRouter);
router.use(landingRouter);
router.use(brandAuthRouter);
router.use(brandProfileRouter);
router.use(categoriesRouter);
router.use(brandSignupFieldsRouter);
router.use(adminBrandsRouter);
router.use(adminConfigRouter);
router.use(adminCategoriesRouter);
router.use(creatorAuthRouter);
router.use(creatorSignupConfigRouter);
router.use(creatorProfileRouter);
router.use(adminCreatorsRouter);
router.use(slabsRouter);
router.use(infoMessagesRouter);
router.use(creatorSignupFieldsRouter);
router.use(creatorHomeRouter);
router.use(adminRejectionReasonsRouter);
router.use(adminFunQuestionsRouter);
router.use(messagesAndTeamRouter);
router.use(brandSearchRouter);
router.use(matchmakingRouter);
router.use(campaignsRouter);
router.use(adminSettingsRouter);
router.use(dealsNegotiationRouter);
router.use(dealChatRouter);
router.use(dealShippingRouter);
router.use(dealPipelineRouter);
router.use(adminRevisionReasonsRouter);
router.use(navBadgesRouter);
router.use(storageRouter);
router.use(uploadImageRouter);
router.use(uploadFileRouter);
router.use(fcmTokenRouter);
router.use(creatorBrandProfileRouter);
router.use(dealExtensionsRouter);
router.use(brandReportsRouter);
router.use(dealReportsRouter);

router.get("/server-time", (_req: Request, res: Response) => {
  res.json({ ts: Date.now() });
});

export default router;
